variable "profile" {}
variable "aws_region" {}
variable "table_name" {}
variable "billing_mode" {}
variable "hash_key" {}
variable "hash_key_type" {}
variable "env" {}
variable "item1_empId" {}
variable "item1_empSal" {}
variable "item1_empFN" {}
variable "item1_empLN" {}
variable "item1_empPH" {}
variable "item2_empId" {}
variable "item2_empSal" {}
variable "item2_empFN" {}
variable "item2_empLN" {}
variable "item2_empPH" {}
